# The config recipe.
# https://rasa.com/docs/rasa/model-configuration/
recipe: default.v1

assistant_id: tuvan_tuyensinh_chatbot

language: vi

pipeline:
  - name: WhitespaceTokenizer
  - name: RegexFeaturizer
  - name: LexicalSyntacticFeaturizer
  - name: CountVectorsFeaturizer
  - name: CountVectorsFeaturizer
    analyzer: char_wb
    min_ngram: 1
    max_ngram: 4
  - name: DIETClassifier
    epochs: 200
  - name: EntitySynonymMapper
  - name: ResponseSelector
    epochs: 200
  - name: FallbackClassifier
    threshold: 0.6
    ambiguity_threshold: 0.1
    fallback_intent_name: "nlu_fallback"

policies:
  - name: MemoizationPolicy
  - name: TEDPolicy
    max_history: 5
    epochs: 300
  - name: RulePolicy
    core_fallback_threshold: 0.3
    core_fallback_action_name: "action_default_fallback"
    enable_fallback_prediction: true

# recipe: default.v1
# assistant_id: tuvan_tuyensinh_chatbot
# language: vi
# pipeline:
#   - name: LanguageModelTokenizer
#     model_name: "./models/phobert"     # <-- dùng model local

#   - name: LanguageModelFeaturizer
#     model_name: "./models/phobert"     # <-- dùng model local

#   - name: RegexFeaturizer
#   - name: LexicalSyntacticFeaturizer

#   - name: RegexEntityExtractor
#     case_sensitive: False
#     use_lookup_tables: True
#     use_regexes: True

#   - name: DIETClassifier
#     epochs: 200

#   - name: EntitySynonymMapper

#   - name: ResponseSelector
#     epochs: 200

#   - name: FallbackClassifier
#     threshold: 0.3
#     ambiguity_threshold: 0.1

# policies:
#   - name: MemoizationPolicy
#   - name: TEDPolicy
#     max_history: 10
#     epochs: 200
#   - name: RulePolicy
