FROM rasa/rasa-sdk:latest

USER root
WORKDIR /app/actions

COPY ./actions /app/actions
COPY requirements.txt /app/requirements.txt
RUN pip install --upgrade pip && pip install --no-cache-dir -r /app/requirements.txt

CMD ["rasa", "run", "actions", "--debug", "--port", "5055"]
