FROM rasa/rasa:latest-full

USER root
WORKDIR /app

# Copy toàn bộ mã nguồn, bao gồm config.yml, domain.yml, credentials.yml, data/, models/
COPY . /app

RUN pip install --upgrade pip \
    && pip install --no-cache-dir -r requirements.txt

# Expose port 5005
EXPOSE 5005

CMD ["rasa", "run", "--enable-api", "--cors", "*", "--debug", "--port", "5005"]